/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewChapters.java
 *
 * Created on 8.8.2010, 16:00:47
 */

package mangastreamdl.gui;

import mangastreamdl.business.Manga;
import mangastreamdl.business.Pair;

import java.util.ArrayList;
import java.util.List;

/**
 * @author sirDarts
 */
public class NewChapters extends javax.swing.JFrame
{

    List<Pair<Manga, String>> l;
    private Gui gui;

    /**
     * Creates new form NewChapters
     */
    private NewChapters()
    {
        initComponents();
    }

    public NewChapters(List<Pair<Manga, String>> l, Gui gui)
    {
        this();
        this.setTitle("New chapters found!");
        this.l = l;
        this.gui = gui;
        jl_chapters.setVisibleRowCount(l.size());
        jl_chapters.setListData(l.toArray());
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jb_download = new javax.swing.JButton();
        jb_close = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_chapters = new javax.swing.JList();
        jb_dlselected = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jb_download.setText("Download all");
        jb_download.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jb_downloadActionPerformed(evt);
            }
        });

        jb_close.setText("Close");
        jb_close.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jb_closeActionPerformed(evt);
            }
        });

        jl_chapters.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = {"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};

            public int getSize()
            {
                return strings.length;
            }

            public Object getElementAt(int i)
            {
                return strings[i];
            }
        });
        jScrollPane1.setViewportView(jl_chapters);

        jb_dlselected.setText("Download selected");
        jb_dlselected.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jb_dlselectedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                layout.createSequentialGroup()
                                                        .addComponent(jb_download)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jb_dlselected)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jb_close, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jb_download)
                                        .addComponent(jb_dlselected)
                                        .addComponent(jb_close))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_downloadActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_jb_downloadActionPerformed
        gui.download(l);
        this.setVisible(false);
    }//GEN-LAST:event_jb_downloadActionPerformed

    private void jb_closeActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_jb_closeActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jb_closeActionPerformed

    private void jb_dlselectedActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_jb_dlselectedActionPerformed
        int[] si = jl_chapters.getSelectedIndices();
        List<Pair<Manga, String>> ret = new ArrayList<>();
        for (int aSi : si)
        {
            ret.add(l.get(aSi));
        }
        System.out.println(ret);
        gui.download(ret);
        this.setVisible(false);
    }//GEN-LAST:event_jb_dlselectedActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton     jb_close;
    private javax.swing.JButton     jb_dlselected;
    private javax.swing.JButton     jb_download;
    private javax.swing.JList       jl_chapters;
    // End of variables declaration//GEN-END:variables

}
